# Generated by Django 3.2.9 on 2021-12-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_rename_book_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='dateTime',
            field=models.CharField(max_length=50),
        ),
    ]
